Change some of the model functions to work better when used concurrently
openstack-charmers/zaza pull request #399
Opened 2020-11-16 12:29 UTC by ajkavanagh

Specifically the async_get_status function can now be 'limited' in the speed at which it re-requests the status from the model.  This, by default, is 'off' (i.e. previous behaviour), but when 'on' the function will limit the speed of response and optionally either return the cached value immediately, or simply wait for the predetermined period (using an async wait) before refetching the status and then returning.

This limits the 'strain' on the controller when doing multiple async / concurrent checks (e.g. series upgrade on a large model).

Secondly, additional functionality to the check_output function to return stderr and stdout.

2020-11-18 17:58 UTC, thedac requested changes
A few nits. Though I think this PR covers quite a few changes that might be better broken up, separating the implementation from the usage. But I won't block on that.

2020-11-18 17:58 UTC, thedac commented on zaza/model.py
> +    :param timeout: Time to wait for contents to appear in file
Time to wait for the file to be missing

2020-11-18 17:58 UTC, thedac commented on zaza/model.py
> +            # output = await unit.run('test -e "{}"; echo $?'.format(path))
Remove?

2020-11-18 17:58 UTC, thedac commented on zaza/model.py
> +            # contents = output.data.get('results')['Stdout']
Remove?

2020-11-18 17:58 UTC, thedac commented on zaza/model.py
> +    :param timeout: Time to wait for contents to appear in file
Time to wait until units are idle

2020-11-18 17:58 UTC, thedac commented on zaza/model.py
> +                    subordinates = u_bag.get('subordinates', [])
The defualt should be {} not []

2020-11-19 10:44 UTC, ajkavanagh commented
> A few nits. Though I think this PR covers quite a few changes that might be better broken up, separating the implementation from the usage. But I won't block on that.

Yes, they do seem a little unrelated.  However, I my (meager) defense, they came about as I was solving the concurrent series upgrade changes in zaza-openstack-tests which needs 'al' of the changes, so I packaged them as one PR.

2020-11-30 21:31 UTC, thedac approved these changes
Merging.

2020-11-30 21:31 UTC, merged