Add a class to refresh all charms in a directory.
openstack-charmers/zaza pull request #676
Opened 2024-11-28 20:40 UTC by lmlg

This patchset adds a class that allows test runs to refresh all charms in a given directory, specified by an environment variable.

The reason behind this change is that the current way of upgrading charms is via the use of the `UpgradeCharmsToPath` class, but it has the disadvantage that it needs the charm name to be known in advance. This is problematic if we're building multiple charms at once and don't know the charm names beforehand.

2025-01-08 08:37 UTC, sabaini requested changes
Heya, thanks @lmlg 
Left some smaller suggestions

2025-01-08 08:37 UTC, sabaini commented on zaza/charm_tests/lifecycle/refresh.py
> +            logging.info('charms path not found')
Logging nit: maybe explicitly state we're not proceeding with refreshing all, sth like

`logging.info("charms artifact dir not set, skipping refreshing all charms")`

2025-01-08 08:37 UTC, sabaini commented on zaza/charm_tests/lifecycle/refresh.py
> +        charms = glob.glob(path + '*.charm')
Suggest to use pathlib for somewhat simpler and more robust path handling

```
from pathlib import Path

path = Path(path).resolve()
charms = list(path.glob('*.charm'))
```

pathlib is in the stdlib since 3.4 -- I don't think we need to cater for older pythons

2025-01-08 08:37 UTC, sabaini commented on zaza/charm_tests/lifecycle/refresh.py
> +            logging.info('no charms found in path')
Logging nit, suggest:

```
logging.info("no charms found in %s", path)
```

2025-01-08 08:37 UTC, sabaini commented on zaza/charm_tests/lifecycle/refresh.py
> +            app_name = charm[len(path):].replace('.charm', '')
When replacing with pathlib.Path this should be changed to

```
app_name = charm.stem
```

2025-01-08 08:37 UTC, sabaini commented on zaza/charm_tests/lifecycle/refresh.py
> +                'juju', 'refresh', '--path', charm, app_name
When replacing with pathlib.Path this should be changed to

```
'juju', 'refresh', '--path', str(charm), app_name
```

2025-01-09 13:46 UTC, sabaini commented
lint error: F401 'glob' imported but unused

2025-01-16 16:31 UTC, UtkarshBhatthere approved these changes
lgtm, thanks @lmlg

2025-01-17 08:13 UTC, sabaini approved these changes
lgtm!

2025-01-17 13:36 UTC, merged